### PR TITLE
Request to add my 'Crystal_Growth_Phase_Field_Model' code to the code gallery.

### PR DESCRIPTION
**Pull request by umairhussaincmm**
This pull request submits the code for the 'Crystal_Growth_Phase_Field_Model' to the code gallery. The code is designed to solve the crystal solidification process using phase field modeling, to demonstrate the conditions of dendritic growth.

### CODE REVIEW

**Comment by marcfehling** [comment]
Hi @umairhussaincmm. Thank you for your contribution!

I see that your code requires deal.II 9.2.0. The version is a bit dated (from 2020), and our testers complain about incompatibilities. Can you make sure that your program compiles with version 9.5.0? We can help you with it if you need assistance.

Currently, our tester complains about `ConstantFunction`, which has been moved to the `Functions` namespace.
```
[ 27%] Building CXX object CMakeFiles/Kobayashi_Parallel.dir/applying_bc.cpp.o
/__w/code-gallery/code-gallery/Crystal_Growth_Phase_Field_Model/applying_bc.cpp: In member function ‘void PhaseFieldSolver::applying_bc()’:
/__w/code-gallery/code-gallery/Crystal_Growth_Phase_Field_Model/applying_bc.cpp:20:47: error: ‘ConstantFunction’ was not declared in this scope; did you mean ‘dealii::Functions::ConstantFunction’?
   20 |                                               ConstantFunction<2>(1., 2),
      |                                               ^~~~~~~~~~~~~~~~
      |                                               dealii::Functions::ConstantFunction
In file included from /__w/code-gallery/code-gallery/Crystal_Growth_Phase_Field_Model/PhaseFieldSolver.h:5,
                 from /__w/code-gallery/code-gallery/Crystal_Growth_Phase_Field_Model/applying_bc.cpp:1:
/usr/local/include/deal.II/base/function.h:410:9: note: ‘dealii::Functions::ConstantFunction’ declared here
  410 |   class ConstantFunction : public Function<dim, RangeNumberType>
      |         ^~~~~~~~~~~~~~~~
/__w/code-gallery/code-gallery/Crystal_Growth_Phase_Field_Model/applying_bc.cpp:20:67: warning: left operand of comma operator has no effect [-Wunused-value]
   20 |                                               ConstantFunction<2>(1., 2),
      |                                                                   ^~
make[2]: *** [CMakeFiles/Kobayashi_Parallel.dir/build.make:104: CMakeFiles/Kobayashi_Parallel.dir/applying_bc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/Kobayashi_Parallel.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by umairhussaincmm** [comment]
> Hi @umairhussaincmm. Thank you for your contribution!
> 
> I see that your code requires deal.II 9.2.0. The version is a bit dated (from 2020), and our testers complain about incompatibilities. Can you make sure that your program compiles with version 9.5.0? We can help you with it if you need assistance.
> 
> Currently, our tester complains about `ConstantFunction`, which has been moved to the `Functions` namespace.


Thank you for the assistance @marcfehling . I have done the necessary modifications. Do I need to create a new pull request for the contribution to be submitted or my job is done here?

**Comment by marcfehling** [comment]
Thank you! There is no need to open another pull request.

**Review by bangerth — APPROVED** [review]
Hi @umairhussaincmm -- outstanding, thank you for offering the program! It was fun chatting with you in Chennai, and nice to see the program we talked about!

Let me see what happens when I merge this!

**Comment by bangerth** [comment]
The documentation is now here: https://dealii.org/developer/doxygen/deal.II/code_gallery_Crystal_Growth_Phase_Field_Model.html
I really like the application -- always nice to see these unstable processes in action :-) Thank you again for adding the program!

Some minor edits are here: https://github.com/dealii/code-gallery/pull/186 If you see anything else that doesn't look right, please let us know and/or make a pull request to fix it.

**Comment by umairhussaincmm** [comment]
Dear Professor @bangerth , Thank you for the encouragement. It was a pleasure meeting you and learn from you first hand.

Thanks for the minor edits too.
